### This is a template file to store secrets related to paperstencil app ##

# Fill in this template and move this as HOME_DIR/.paperstencil/secret.yml. If you are planning to store secret.yml,
# at some other place, change lib/paperstencil_config.rb accordingly.
# Be sure to restart your server when you modify secret.yml file.


### Rails cookie related
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure your secret_key_base is kept private
# if you're sharing your code publicly.
rails:
 secret_key_base: <<Rails will use this key to encrypt cookies>>


# Amazon Simple email service related. Used in production environment to send out emails.
aws_ses:
 access_key_id: <<aws ses access id>>
 secret_access_key: <<aws ses secret>>
